name: Update Pom Version

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-pom-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Pom Version
      run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}

    - name: Commit changes
      run: |
        git config user.email "github-actions@github.com"
        git config user.name "GitHub Actions"
        git add pom.xml
        git commit -m "Update pom.xml version to ${{ github.event.release.tag_name }}"
        git push
        
